/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.springbootapp.model;

public abstract class Figura {

	public Figura() {
		super();
	}

	/**
	 * @return the area
	 */
	public abstract double getArea();
	public abstract String toString();

	public static void checkValue(double value) {
		if (value <= 0.0) {
			throw new IllegalArgumentException();
		}
	}
	
	
	
}